MODEL:
  META_ARCHITECTURE: "DomainAdaptiveRCNN"
  IMG_FDA_ON: True
  INSTANCE_FDA_ON: True
  FDA_CONSISTENCY_REGULARIZATION_ON: True
  BACKBONE:
    NAME: "build_vgg_backbone"
  VGG:
    OUT_FEATURES: ["conv5_3"]
  # WEIGHTS: "https://download.pytorch.org/models/vgg16-397923af.pth"
  # WEIGHTS: "/lhome/peizhli/projects/model_zoo/vgg16-397923af.pth"
  ANCHOR_GENERATOR:
    SIZES: [[128, 256, 512]]
  RPN:
    IN_FEATURES: ["conv5_3"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
    NMS_THRESH: 0.7
  IMG_FDA_HEAD:
    NAME: "ImageFDAHead"
    IN_FEATURES: ["conv5_3"]
  ROI_HEADS:
    NAME: "DomainAdaptiveROIHeads"
    IN_FEATURES: ["conv5_3"]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  INSTANCE_FDA_HEAD:
    NAME: "InstanceFDAHead"
    POOLER_RESOLUTION: 14
DATASETS:
  ROOT_DIR: "/lhome/peizhli/datasets"
  # Available Datasets: "Cityscapes_train", "FoggyCityscapes_train", "Sim10k_train" or "Kitti_train"  
  TRAIN: ("Sim10k_train", "Cityscapes_train",)
  # Available Datasets: "Cityscapes_val", "FoggyCityscapes_val", "Sim10k_val" or "Kitti_val"
  TEST: ("Cityscapes_val",)
  EQUAL_FREQUENCY: True
DATALOADER:
  SAMPLER_TRAIN: EquallyDatasetsTrainingSampler
FOOC:
  SOURCE:
    COMPUTE_DET_LOSS: True
  TARGET:
    COMPUTE_DET_LOSS: False
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 1e-3
  GAMMA: 0.1
  STEPS: (50000,)
  MAX_ITER: 70000
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-4
INPUT:
  MIN_SIZE_TRAIN: (500,)
  MIN_SIZE_TEST: 500
VERSION: 2
TEST:
  EVAL_PERIOD: 5000
OUTPUT_DIR: "/lhome/peizhli/projects/FOOC/baseline/sim10k2cityscapes_2"
